require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.toggleterm"
require "user.nvim-tree"
require "user.bufferline"
require "user.treesitter"
require "user.comment"
require "user.alpha"

vim.cmd "highlight comment guifg=#6d8d57"
